title: The Bash Junkie
description: >
  Short posts on bash scripting.
  Because there is always something more to learn.

markdown: redcarpet2
redcarpet:
    extensions: ["strikethrough"]
theme: minima

